#TODO split out message and action codes into two files

EVENT_MESSAGE_TYPE = 2
EVENT_ACTION_TYPE = 3

PERSON_1_TYPE = 12
PLAYER_1_ID = 13
PERSON_2_TYPE = 19
PLAYER_2_ID = 20
PERSON_3_TYPE = 26
PLAYER_3_ID = 27

HOME_PLAYER = 4
AWAY_PLAYER = 5

SCORE = 10

HOME_DESCRIPTION = 7
NEUTRAL_DESCRIPTION = 8
AWAY_DESCRIPTION = 9